build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Nagesh P - Developer"
    email: "ngpta@eazybank.com"
  onCallSupport:
    - (555) 456-2176
    - (555) 764-8934